export const coffee = [
  {
    id: 5534,
    uid: "6e5738e2-a9db-4bdf-a60e-f2b653233f0f",
    blend_name: "Morning Nuts",
    origin: "Kirinyaga, Kenya",
    variety: "Kaffa",
    notes: "delicate, juicy, dates, hazelnut, sundried tomato",
    intensifier: "crisp",
  },
  {
    id: 7637,
    uid: "94ef283a-3d39-4c4a-ae5c-df00a91f9698",
    blend_name: "Spilt Cake",
    origin: "Chiriqui, Panama",
    variety: "Pacamara",
    notes: "structured, syrupy, cinnamon, carmel, mushroom",
    intensifier: "unbalanced",
  },
  {
    id: 9097,
    uid: "d97c0cdd-25a7-4af7-bb4d-8ada13e97493",
    blend_name: "Brooklyn Level",
    origin: "Boyacá, Colombia",
    variety: "Geisha",
    notes: "complex, creamy, smokey, hazelnut, soy sauce",
    intensifier: "mild",
  },
  {
    id: 104,
    uid: "0b210826-979c-4ca4-b6bf-1c43ba878b3a",
    blend_name: "Jacked Level",
    origin: "Sul Minas, Brazil",
    variety: "Pink Bourbon",
    notes: "complex, coating, soil, magnolia, maple syrup",
    intensifier: "delicate",
  },
  {
    id: 2165,
    uid: "354ba60e-09f3-4a65-8e64-7b4ab6c98a70",
    blend_name: "Reg's Level",
    origin: "Kayanza, Burundi",
    variety: "Typica",
    notes: "deep, round, pineapple, rye, green-tea",
    intensifier: "clean",
  },
  {
    id: 8255,
    uid: "8ee5e3b4-b898-433e-995d-99f87cd21c72",
    blend_name: "The Cake",
    origin: "Tapanuli, Sumatra",
    variety: "SL34",
    notes: "dirty, slick, orange creamsicle, fresh bread, black-tea",
    intensifier: "astringent",
  },
  {
    id: 7186,
    uid: "c180d719-0a4e-47d6-a608-b57b65f1fe37",
    blend_name: "Melty Enlightenment",
    origin: "Cerrado, Brazil",
    variety: "S.4",
    notes: "vibrant, round, plum, coconut, lemongrass",
    intensifier: "faint",
  },
  {
    id: 8322,
    uid: "5f2afe4c-63bd-4c1a-8aea-d6a74a6de9f8",
    blend_name: "Chocolate Star",
    origin: "Kayanza, Burundi",
    variety: "Typica",
    notes: "clean, velvety, strawberry, bittersweet chocolate, cacao nibs",
    intensifier: "bright",
  },
  {
    id: 9907,
    uid: "1fa175c5-7118-494c-8690-f41c94a666c2",
    blend_name: "Strong Mug",
    origin: "Kayanza, Burundi",
    variety: "Mokka",
    notes: "wild, chewy, corriander, milk chocolate, mango",
    intensifier: "deep",
  },
  {
    id: 9709,
    uid: "cf25dede-5a53-433f-9352-8dbb5c37556c",
    blend_name: "Heart Mug",
    origin: "Huila, Colombia",
    variety: "SL34",
    notes: "soft, full, peanut, almond, hibiscus",
    intensifier: "pointed",
  },
  {
    id: 1570,
    uid: "f63f4cc4-a1d6-4fa3-bf88-0bd2802a7889",
    blend_name: "Cascara Light",
    origin: "Matagalpa, Nicaragua",
    variety: "Sarchimor",
    notes: "mild, creamy, hay, tamarind, honeydew",
    intensifier: "deep",
  },
  {
    id: 7624,
    uid: "b4beda81-3629-40e9-a94c-084468e7a44f",
    blend_name: "Holiday Equinox",
    origin: "Mt. Kenya, Kenya",
    variety: "Typica",
    notes: "rounded, juicy, white grape, golden raisin, nougat",
    intensifier: "soft",
  },
  {
    id: 340,
    uid: "b801d8d8-d8e4-4692-b73e-dc39cb04edef",
    blend_name: "KrebStar Mug",
    origin: "Sul Minas, Brazil",
    variety: "Mokka",
    notes: "muted, velvety, dates, carbon, tobacco",
    intensifier: "deep",
  },
  {
    id: 8237,
    uid: "5845540c-8e1b-4b05-bdc3-81802d25b55e",
    blend_name: "Winter Town",
    origin: "Veracruz, Mexico",
    variety: "Ennarea",
    notes: "vibrant, round, lemon verbena, cocoa powder, corriander",
    intensifier: "dirty",
  },
  {
    id: 4194,
    uid: "5980057e-400c-40fa-b7ca-1457174f47f7",
    blend_name: "Morning Look",
    origin: "Gayo, Sumatra",
    variety: "Kona",
    notes: "dirty, smooth, red grape, hazelnut, fresh wood",
    intensifier: "unbalanced",
  },
  {
    id: 101,
    uid: "e20c77a0-5f4a-4096-9955-e9d446608c44",
    blend_name: "Major Been",
    origin: "Kayanza, Burundi",
    variety: "Kent",
    notes: "dry, slick, orange creamsicle, burnt sugar, marzipan",
    intensifier: "pointed",
  },
  {
    id: 7827,
    uid: "8f224865-d919-4bd7-af0a-f2ef01c76e57",
    blend_name: "Blue Treat",
    origin: "Guanacaste, Costa Rica",
    variety: "Colombia",
    notes: "sharp, watery, green grape, white grape, lavender",
    intensifier: "crisp",
  },
  {
    id: 195,
    uid: "a31d14cc-2c05-4a08-b3a6-ccc875c01e7d",
    blend_name: "Dark Solstice",
    origin: "Hirazi, Yemen",
    variety: "Sarchimor",
    notes: "mild, tea-like, carbon, plum, white grape",
    intensifier: "pointed",
  },
  {
    id: 4526,
    uid: "476122b7-26b3-4c7e-ad2b-8f36a7373a6c",
    blend_name: "Bluebery Solstice",
    origin: "Mogiana, Brazil",
    variety: "Agaro",
    notes: "crisp, full, bergamot, liquorice, papaya",
    intensifier: "dense",
  },
  {
    id: 4137,
    uid: "15d43c83-fdd7-48a6-ab30-d407ae28df64",
    blend_name: "Joe Been",
    origin: "San Luis Potosi, Mexico",
    variety: "SL28",
    notes: "deep, velvety, sage, carmel, lychee",
    intensifier: "vibrant",
  },
];
